MyTriggers/framework/objects/MyTriggerSetting__mdt/MyTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>MyTrigger Settings let you define trigger handler classes to run on the selected sObject and trigger event</description>
    <label>MyTrigger Setting</label>
    <pluralLabel>MyTrigger Settings</pluralLabel>
</CustomObject>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should the trigger class be run? Only uncheck this with extreme caution as it disabling an important triggers could cause data inconsistency</description>
    <inlineHelpText>Should the trigger class be run? Only uncheck this with extreme caution as it disabling an important triggers could cause data inconsistency</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The name of the ApexClass that should run for configured Trigger Events. Use the Namespace Prefix field if the class should have a namespace</description>
    <inlineHelpText>The name of the ApexClass that should run for configured Trigger Events. Use the Namespace Prefix field if the class should have a namespace</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/ClassNamespacePrefix__c.field-meta.xml
<CustomField>
    <fullName>ClassNamespacePrefix__c</fullName>
    <description>Namespace prefix of trigger handler apex class</description>
    <inlineHelpText>Namespace prefix of trigger handler apex class</inlineHelpText>
    <label>Class Namespace Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Trigger event to run this handler</description>
    <inlineHelpText>Trigger event to run this handler</inlineHelpText>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BeforeInsert</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
                <label>BeforeUpdate</label>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
                <label>BeforeDelete</label>
            </value>
            <value>
                <fullName>BEFORE_UNDELETE</fullName>
                <label>BeforeUndelete</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
                <label>AfterInsert</label>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
                <label>AfterUpdate</label>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <label>AfterDelete</label>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
                <label>AfterUndelete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/IsBypassAllowed__c.field-meta.xml
<CustomField>
    <fullName>IsBypassAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, will this setting will not be run for any user that has the Bypass MyTrigger Custom Permission assigned</description>
    <inlineHelpText>If true, will this setting will not be run for any user that has the Bypass MyTrigger Custom Permission assigned</inlineHelpText>
    <label>Allow Bypass</label>
    <type>Checkbox</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Handlers are run in ascending order of this field for a given sObject and Event. If order is unimportant, you can just use 0.</description>
    <inlineHelpText>Handlers are run in ascending order of this field for a given sObject and Event Handlers are run in ascending order of this field for a given sObject and Event. If order is unimportant, you can just use 0.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <description>The sObject for which a Trigger implementing MyTrigger exists and for which a specific class should run</description>
    <inlineHelpText>Choose to sObject for which you want to run the class</inlineHelpText>
    <label>sObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>TriggerHandlerSettings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

MyTriggers/framework/objects/MyTriggerSetting__mdt/fields/sObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>sObjectAPIName__c</fullName>
    <description>Should only be used IF a sObject type is not available in the sObject picklist. Picklist takes precedence over this field. Field requires fully qualified API Name (namespace__CustomObject__c)</description>
    <inlineHelpText>Should only be used IF a sObject type is not available in the sObject picklist. Picklist takes precedence over this field. Field requires fully qualified API Name (namespace__CustomObject__c)</inlineHelpText>
    <label>sObject Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MyTriggers/framework/ux/classes/MyTriggerViewerController.cls
public class MyTriggerViewerController implements Metadata.DeployCallback {
    /**
     * Returns list of all triggerHandlerSetting
     * @return all triggerHandlerSetting
     */
    @AuraEnabled
    public static List<MyTriggerSetting__mdt> getAllTriggerHandlerSettings(){
        List<MyTriggerSetting__mdt> triggerHandlerSettings;

            triggerHandlerSettings = new List<MyTriggerSetting__mdt>(
                [SELECT DeveloperName, 
                        Label,
                        ClassNamespacePrefix__c, 
                        Event__c, 
                        sObject__c,
                        sObject__r.QualifiedApiName, 
                        sObjectAPIName__c,
                        Class__c, 
                        Order__c,
                        Description__c,
                        Active__c,
                        IsBypassAllowed__c
                FROM MyTriggerSetting__mdt
                WHERE Active__c = true
                ORDER BY Order__c, 
                         DeveloperName ASC]);

        System.debug(JSON.serialize(triggerHandlerSettings));
        return triggerHandlerSettings;
    }

    /* Below method recieves the 2 parameters 
       1 - Metadata.DeployResult => Object of MetadataContainer class where this method has been implemented.
       2 - Metadata.DeployCallbackContext => Object of the class where this method has been implemented
   */
    public void handleResult(Metadata.DeployResult result,
                             Metadata.DeployCallbackContext context) {
        if (result.status == Metadata.DeployStatus.Succeeded) {
            System.debug('success');
        } else {
            // Deployment was not successful
        }
    }

	@AuraEnabled(cacheable=true)
    public static String updateMdt(String metadataAsString) {
		System.debug(metadataAsString);
		List<MyTriggerSetting__mdt> metadataRecords = (List<MyTriggerSetting__mdt>) JSON.deserialize(metadataAsString, List<MyTriggerSetting__mdt>.class); 
		Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
		
		for (MyTriggerSetting__mdt currentMetadataRecord : metadataRecords) {
			Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();

			customMetadata.fullName = 'MyTriggerSetting.'+currentMetadataRecord.DeveloperName;
			customMetadata.label = currentMetadataRecord.Label;

			customMetadata.values.add(createField('Class__c', currentMetadataRecord.Class__c));
			customMetadata.values.add(createField('Description__c', currentMetadataRecord.Description__c));
			customMetadata.values.add(createField('Event__c', currentMetadataRecord.Event__c));
			customMetadata.values.add(createField('sObject__c', currentMetadataRecord.sObject__c));
			customMetadata.values.add(createField('sObjectAPIName__c', currentMetadataRecord.sObjectAPIName__c));
			customMetadata.values.add(createField('IsBypassAllowed__c', currentMetadataRecord.IsBypassAllowed__c));
			customMetadata.values.add(createField('Active__c', currentMetadataRecord.Active__c));
			customMetadata.values.add(createField('Order__c', currentMetadataRecord.Order__c));
			customMetadata.values.add(createField('ClassNamespacePrefix__c', currentMetadataRecord.ClassNamespacePrefix__c));

			mdContainer.addMetadata(customMetadata);
		}
		MyTriggerViewerController callback = new MyTriggerViewerController();
		Id jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);
		
		return jobId;
	}

	@AuraEnabled
    public static Map<String,Object> checkMdt(String deploymentId) {
		Map<String,Object> result = new Map<String,Object>();
		
		MetadataService.MetadataPort service = createService();
		MetadataService.DeployResult deployResult = service.checkDeployStatus(deploymentId, true);
		if(deployResult.done) {
			System.debug('Deployment complete');
			result.put('isSuccess', true);
			result.put('isDeployed', true);
			result.put('message', 'Deployment complete');
			// Deployment errors?
			if(deployResult.details!=null && deployResult.details.componentFailures!=null) {
				for(MetadataService.DeployMessage deployMessage : deployResult.details.componentFailures) {
					if(deployMessage.problem!=null) {
						String errorMsg = deployMessage.fileName + 
									' (Line: ' + deployMessage.lineNumber + ': Column:' + deployMessage.columnNumber + ') : ' + 
										deployMessage.problem;
						result.put('isSuccess', false);
						result.put('isDeployed', false);
						result.put('error', errorMsg);
					}
				}
			}
		} else {
			result.put('isSuccess', true);
			result.put('isDeployed', false);
			result.put('message', 'Deploying...');
		}

		return result;
	}

	public static Metadata.CustomMetadataValue createField(String fieldName, String value) {
		Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
		customField.field = fieldName;
		customField.value = value;
		return customField;
	}

	public static Metadata.CustomMetadataValue createField(String fieldName, Boolean value) {
		Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
		customField.field = fieldName;
		customField.value = value;
		return customField;
	}

	public static Metadata.CustomMetadataValue createField(String fieldName, Decimal value) {
		Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
		customField.field = fieldName;
		customField.value = value;
		return customField;
	}

	private static MetadataService.MetadataPort createService() { 
		MetadataService.MetadataPort service = new MetadataService.MetadataPort();
		service.SessionHeader = new MetadataService.SessionHeader_element();
		service.SessionHeader.sessionId = UserInfo.getSessionId();
		return service;		
	}
     
	@AuraEnabled(cacheable=true)
	public static List<Object> getSobjects(){
		List<Object> result = new List<Object>();
        for (EntityDefinition entity : [
				SELECT
					DeveloperName,
					Id,
					Label
				FROM EntityDefinition
				where IsWorkflowEnabled = true 
				order by Label ]
		) {
            result.add(
				new SobjectItem(
					entity.DeveloperName, 
					entity.Label
				)
			);
        }
        return result;
	}

	public class SobjectItem {
		@AuraEnabled
		public String value;
		@AuraEnabled
		public String label;

		public SobjectItem(String value, String label) {
			this.value = value;
			this.label = label;
		}
	}
}